### PR TITLE
sfx6008 - added Wake on lan

### PR DESCRIPTION
**Pull request by ims21**

### CODE REVIEW

**Comment by neo-pli-bsps** [comment]
You're sure the box supports this?

**Comment by ims21** [comment]
Of course - it works. I never adding non working things...

**Comment by neo-pli-bsps** [comment]
Hey @WanWizard, go back to bed you! :rofl:

**Comment by ims21** [comment]
Is it this repo used for build develop or no?

**Comment by neo-pli-bsps** [comment]
Yes, but all submodules are pinned (that is how submodules work), so if you want to test, you need to do a `git checkout HEAD` in your local meta-octagon.

**Pull request merged**
